### ISSUE TITLE
There is no 'force' option on make report

### ISSUE THREAD

**Issue by jetexe** [avto-dev/b2b-api-php-laravel#2]
### Is your feature request related to a problem? Please describe.

Package avto-dev/b2b-api-php, was updated: added `is_force` flag in avto-dev/b2b-api-php#6

### Describe the solution you'd like

Need to add `is_force` flag to `makeReport` method and proxy it to avto-dev/b2b-api-php

**Comment by tarampampam** [comment]
Closed https://github.com/avto-dev/b2b-api-php-laravel/pull/3
