### ISSUE TITLE
Add Lumen support

### ISSUE THREAD

**Issue by tesler** [avto-dev/b2b-api-php-laravel#7]
### Is your feature request related to a problem? Please describe.

Add [Lumen](https://github.com/laravel/lumen-framework) support.

### Describe the solution you'd like

Change the type of `$app` from `Illuminate\Foundation\Application` to `Illuminate\Container\Container`.

## Additional context

Using Lumen instead of Laravel resulted in an error:
```
Argument 1 passed to AvtoDev\B2BApiLaravel\B2BApiServiceProvider::AvtoDev\B2BApiLaravel\{closure}() must be an instance of Illuminate\Foundation\Application, instance of Laravel\Lumen\Application given...
```
Both [`Illuminate\Foundation\Application`](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Application.php) and [`Laravel\Lumen\Application`](https://github.com/laravel/lumen-framework/blob/5.7/src/Application.php) extends [`Illuminate\Container\Container`](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Container/Container.php).

**Comment by tarampampam** [comment]
PR merged.

Release: https://github.com/avto-dev/b2b-api-php-laravel/releases/tag/v2.6.0

Thx for your contribution!
